/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodavelha;

import javax.swing.JOptionPane;

/**
 *
 * @author Tarcyo
 */
public class Telinha extends javax.swing.JFrame {

    @Override
    public void setTitle(String title) {
        super.setTitle(title); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Telinha
     */
    public Telinha() {

        initComponents();
        this.setTitle("Jogo Da Velha");
        Mostra.setText(escolhido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        botão2 = new javax.swing.JButton();
        botão5 = new javax.swing.JButton();
        botão4 = new javax.swing.JButton();
        botão1 = new javax.swing.JButton();
        botão7 = new javax.swing.JButton();
        botão8 = new javax.swing.JButton();
        botão3 = new javax.swing.JButton();
        botão6 = new javax.swing.JButton();
        botão9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Mostra = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botão2.setText("Espaço livre 2 ");
        botão2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão2ActionPerformed(evt);
            }
        });

        botão5.setText("Espaço Livre 5");
        botão5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão5ActionPerformed(evt);
            }
        });

        botão4.setText("Espaço livre 4");
        botão4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão4ActionPerformed(evt);
            }
        });

        botão1.setText("Espaço livre 1 ");
        botão1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão1ActionPerformed(evt);
            }
        });

        botão7.setText("Espaço Livre 7");
        botão7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão7ActionPerformed(evt);
            }
        });

        botão8.setText("Espaço livre 8");
        botão8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão8ActionPerformed(evt);
            }
        });

        botão3.setText("Espaço livre 3");
        botão3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão3ActionPerformed(evt);
            }
        });

        botão6.setText("Espaço Livre 6");
        botão6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão6ActionPerformed(evt);
            }
        });

        botão9.setText("Espaço livre 9");
        botão9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botão9ActionPerformed(evt);
            }
        });

        jLabel1.setText("Rodada do:");

        Mostra.setText("jLabel2");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botão1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botão5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botão3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mostra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botão3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(botão2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botão6, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(botão4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botão7, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(botão8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botão9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Mostra))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botão1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão1ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão1.setText("X");
            rodada = "O";
            botão1.disable();
            botão1.disable();
            botão1.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão1.setText("O");
            rodada = "X";
            botão1.disable();
            botão1.setEnabled(false);
        }
       boolean l= verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
       if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão1ActionPerformed

    private void botão4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão4ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão4.setText("X");
            rodada = "O";
            botão4.disable();
            botão4.disable();
            botão4.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão4.setText("O");
            rodada = "X";
            botão4.disable();
            botão4.setEnabled(false);
        }
        boolean l= verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
         if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão4ActionPerformed

    private void botão2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão2ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão2.setText("X");
            rodada = "O";
            botão2.disable();
            botão2.disable();
            botão2.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão2.setText("O");
            rodada = "X";
            botão2.disable();
            botão2.setEnabled(false);
        }
        boolean l= verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
        if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
        if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão2ActionPerformed

    private void botão3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão3ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão3.setText("X");
            rodada = "O";
            botão3.disable();
            botão3.disable();
            botão3.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão3.setText("O");
            rodada = "X";
            botão3.disable();
            botão3.setEnabled(false);
        }
     boolean l=    verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
     if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão3ActionPerformed

    private void botão5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão5ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão5.setText("X");
            rodada = "O";
            botão5.disable();
            botão5.disable();
            botão5.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão5.setText("O");
            rodada = "X";
            botão5.disable();
            botão5.setEnabled(false);
        }
        boolean l= verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
        if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão5ActionPerformed

    private void botão6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão6ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão6.setText("X");
            rodada = "O";
            botão6.disable();
            botão6.disable();
            botão6.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão6.setText("O");
            rodada = "X";
            botão6.disable();
            botão6.setEnabled(false);
        }
       boolean l=  verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
       if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão6ActionPerformed

    private void botão7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão7ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão7.setText("X");
            rodada = "O";
            botão7.disable();
            botão7.disable();
            botão7.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão7.setText("O");
            rodada = "X";
            botão7.disable();
            botão7.setEnabled(false);
        }
       boolean l=  verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
       if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão7ActionPerformed

    private void botão8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão8ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão8.setText("X");
            rodada = "O";
            botão8.disable();
            botão8.disable();
            botão8.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão8.setText("O");
            rodada = "X";
            botão8.disable();
            botão8.setEnabled(false);
        }
       boolean l=  verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
       if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão8ActionPerformed

    private void botão9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botão9ActionPerformed
        if (rodada.equals("X")) {
            this.Mostra.setText("O");
            botão9.setText("X");
            rodada = "O";
            botão9.disable();
            botão9.disable();
            botão9.setEnabled(false);
        } else {
            this.Mostra.setText("X");
            botão9.setText("O");
            rodada = "X";
            botão9.disable();
            botão9.setEnabled(false);
        }
      boolean l=   verifica(botão1.getText(),botão2.getText(),botão3.getText(),botão4.getText(),botão5.getText(),botão6.getText(),botão7.getText(),botão8.getText(),botão9.getText());
      if(l){
           this.setVisible(false);
           String a;
           if(rodada.equals("X")){
               a="O";
           }else{
               a="X";
           }
           JOptionPane.showMessageDialog(rootPane, "Quem ganhou foi o:"+a+"!");
           JOptionPane.showMessageDialog(rootPane, "Até a proxima!!!!");
           this.disable();
           this.dispose();
           
       }
    }//GEN-LAST:event_botão9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Telinha().setVisible(true);

            }

        });
    }
    static JogoDaVelha jogodaVelha = new JogoDaVelha();
    static String escolhido = jogodaVelha.sorteado;
    static String rodada = escolhido;
    static boolean logico = true;

    private static boolean verifica(String b1, String b2, String b3, String b4, String b5, String b6, String b7, String b8, String b9) {
        if(b1.equals(b2)&& b2.equals(b3)){
            return true;
        }
        if(b4.equals(b5)&& b5.equals(b6)){
            return true;
        }
        if(b7.equals(b8)&& b8.equals(b9)){
            return true;
        }
        if(b1.equals(b5)&& b5.equals(b9)){
            return true;
        }
        if(b3.equals(b5)&& b5.equals(b7)){
            return true;
        }
        if(b1.equals(b7)&& b7.equals(b4)){
            return true;
        }
        if(b2.equals(b5)&& b5.equals(b8)){
            return true;
        }
        if(b3.equals(b6)&& b6.equals(b9)){
            return true;  
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mostra;
    private javax.swing.JButton botão1;
    private javax.swing.JButton botão2;
    private javax.swing.JButton botão3;
    private javax.swing.JButton botão4;
    private javax.swing.JButton botão5;
    private javax.swing.JButton botão6;
    private javax.swing.JButton botão7;
    private javax.swing.JButton botão8;
    private javax.swing.JButton botão9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
